-- phpMyAdmin SQL Dump
-- version 2.11.9.5
-- http://www.phpmyadmin.net
--
-- 호스트: localhost
-- 처리한 시간: 12-12-08 22:41 
-- 서버 버전: 5.1.38
-- PHP 버전: 5.2.10

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- 데이터베이스: `dydrn33`
--

-- --------------------------------------------------------

--
-- 테이블 구조 `board`
--

CREATE TABLE IF NOT EXISTS `board` (
  `no` int(11) NOT NULL AUTO_INCREMENT,
  `subject` varchar(255) NOT NULL,
  `sub_id` varchar(30) NOT NULL,
  `wtype` varchar(100) NOT NULL,
  `content` mediumtext NOT NULL,
  `wdate` datetime NOT NULL,
  `wdate2` datetime NOT NULL,
  `tags` varchar(100) NOT NULL,
  PRIMARY KEY (`no`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=129 ;

--
-- 테이블의 덤프 데이터 `board`
--

INSERT INTO `board` (`no`, `subject`, `sub_id`, `wtype`, `content`, `wdate`, `wdate2`, `tags`) VALUES
(57, 'php myadmin 접속에러', 'other', '', 'Myadmin을 접속하려고 할 때 가끔씩 아래처럼 에러가 나기도 한다.\r\nCannot start session without errors, please check errors given in your PHP and/or webserver log file and configure your PHP installation properly.\r\n\r\n해결방법 \r\nBack Space -&gt; F5 -&gt; Login', '2012-12-05 16:39:26', '2012-12-05 18:59:57', ''),
(58, 'jquery at w3schoos.com', 'eng', '', 'The jQuery syntax is tailor made for selecting HTML elements and perform some action on the element(s).\r\n\r\nsyntax (신텍스) : 문법\r\ntailor (테일럴) : 맞추다.\r\nManipulation : 조작\r\n\r\n$.noConflict();\r\nconflict : 갈등, 물리적 갈등', '2012-12-05 19:15:41', '2012-12-05 21:15:58', ''),
(59, 'jquery Start', 'Jquery', '', '$(document).ready(function(){\r\n});\r\nor\r\n$(function(){\r\n});\r\n로드 되었을 때 이다. 둘 다 같은 효과가 있다.', '2012-12-05 19:17:03', '0000-00-00 00:00:00', ''),
(60, 'jquery selectors', 'Jquery', '', '$(&quot;*&quot;) : 모든 element를 선택\r\n$(this) : 현제 element를 선택\r\n$(&quot;p.intro&quot;) : p 중에 class=''intro''인 것을 선택\r\n$(&quot;p:first&quot;) : 가장 첫번째에 있는 p를 선택\r\n$(&quot;ul li:first&quot;) : ul안에 있는 li중에 가장 첫번째를 선택\r\n$(&quot;ul li:first-child&quot;) : ul에서 첫번째있는 li를 선택\r\n$(&quot;[href]&quot;) : href 속성을 가지고 있는 태그를 선택\r\n$(&quot;a[target=''_blank'']&quot;) : a에서 target이 _blank인 것을 선택\r\n$(&quot;a[target!=''_blank'']&quot;) : a에서 target이 _blank가 아닌 것을 선택\r\n$(&quot;:button&quot;) : button태그나 input type=''button''을 선택\r\n$(&quot;tr:even&quot;) : even를 쓰면 홀수 층를 선택\r\n$(&quot;tr:odd&quot;) : odd를 쓰면 짝수 층을 선택', '2012-12-05 19:30:49', '2012-12-06 09:25:19', ''),
(61, 'Event Methods', 'Jquery', '', 'click() 클릭했을때\r\ndblclick() 더블클릭했을 때\r\nmouseenter() 마우스를 올렸을 때\r\nmouseleave() 마우스를 떠 났을 때\r\nmousedown() 마우스로 눌렀을 때\r\nmouseup() 마우스가 때 질때\r\nhover(mouseenter,mouseleave) 두개를 합침\r\nfocus() 포커스 생길때\r\nblur() 포커스 사라질때', '2012-12-05 19:43:03', '2012-12-06 10:14:39', ''),
(62, 'jquery effects', 'Jquery', '', 'hide(speed,callback)&nbsp;숨김\r\nshow(speed,callback)&nbsp;보여줌\r\ntoggle(speed,callback)&nbsp;숨기고&nbsp;보여주는&nbsp;것을&nbsp;하나로&nbsp;함\r\n\r\nspeed&nbsp;=&nbsp;&quot;slow&quot;,&nbsp;&quot;fast&quot;,&nbsp;&quot;milliseseconds&quot;\r\n\r\nfadeIn(speed,callback)&nbsp;서서히&nbsp;나타남\r\nfadeOut(speed,callback)&nbsp;서서히&nbsp;사라짐\r\nfadeToggle(speed,callback)&nbsp;둘을&nbsp;합침\r\nfadeTo(speed,opacity,callback)&nbsp;opacity를&nbsp;0에서&nbsp;1까지&nbsp;투명도를&nbsp;줄&nbsp;수&nbsp;있음\r\n\r\nslideDown(speed,callback)&nbsp;아래로&nbsp;내려가는&nbsp;슬라이드효과\r\nslideUp(speed,callback)&nbsp;위로&nbsp;올라가는&nbsp;슬라이트효과\r\nslideToggle(speed,callback)&nbsp;\r\n\r\nAnimation\r\nanimate({params},speed,callback)&nbsp;애니메이션&nbsp;효과를&nbsp;준다.\r\n$(function(){\r\n&nbsp;&nbsp;&nbsp;&nbsp;$(&quot;div&quot;).animation({\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;width:100px,\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;height:300px\r\n&nbsp;&nbsp;&nbsp;&nbsp;});\r\n});\r\n\r\nstop()&nbsp;애니메이션&nbsp;효과를&nbsp;멈춤\r\n\r\nJquery&nbsp;Method&nbsp;Chaining\r\n$(&quot;p&quot;).css(&quot;color&quot;,&quot;red&quot;).slideUp(2000).slideDown(2000);\r\n이렇게&nbsp;하면&nbsp;slideup&nbsp;후&nbsp;slidedown이&nbsp;됨', '2012-12-05 19:55:45', '2012-12-06 10:23:07', ''),
(63, 'Jquery HTML', 'Jquery', '', 'Jquery&nbsp;get\r\n$(&quot;p&quot;).text()&nbsp;p안에&nbsp;텍스트만&nbsp;가져온다.\r\n$(&quot;p&quot;).html()&nbsp;p안에&nbsp;태그까지&nbsp;가져온다.\r\n$(&quot;input&quot;).val()&nbsp;input&nbsp;태그의&nbsp;value를&nbsp;가져온다.\r\n$(&quot;input&quot;).attr(&quot;src&quot;);&nbsp;input&nbsp;태그의&nbsp;src를&nbsp;가져온다.\r\n\r\nJquery&nbsp;set\r\n$(&quot;p&quot;).text(&quot;텍스트쓰기&quot;)\r\n$(&quot;p&quot;).html(&quot;&lt;b&gt;태그&nbsp;포함하고&nbsp;쓰기&lt;/b&gt;&quot;)\r\n$(&quot;input&quot;).val(&quot;value쓰기&quot;)\r\n$(&quot;a&quot;).attr(&quot;href&quot;,&quot;http&quot;//www.naver.com&quot;);\r\n$(&quot;a&quot;).attr({\r\n&nbsp;&nbsp;&nbsp;&quot;href&quot;&nbsp;:&nbsp;&quot;http://www.naver.com&quot;,\r\n&nbsp;&nbsp;&nbsp;&quot;title&quot;&nbsp;:&nbsp;&quot;a태그&quot;\r\n});\r\n\r\nCallback&nbsp;function&nbsp;text(),&nbsp;html(),&nbsp;val()은&nbsp;callback&nbsp;function&nbsp;이&nbsp;있다.\r\n$(&quot;p&quot;).text(function(i,origText){\r\nreturn&nbsp;&quot;선택된&nbsp;갯수&quot;&nbsp;+&nbsp;i&nbsp;+&nbsp;&quot;&nbsp;그리고&nbsp;텍스트&nbsp;:&nbsp;&quot;+origText;\r\n});\r\n\r\nJquery&nbsp;Add\r\n$(&quot;p&quot;).append(&quot;p안에&nbsp;있는&nbsp;텍스트&nbsp;뒤에&nbsp;삽입&quot;)\r\n$(&quot;p&quot;).prepend(&quot;p안에&nbsp;있는&nbsp;텍스트&nbsp;앞에&nbsp;삽입&quot;)\r\n$(&quot;img&quot;).after(&quot;태그&nbsp;다음에&nbsp;출력&quot;)\r\n$(&quot;img&quot;).before(&quot;태그&nbsp;이전에&nbsp;출력&quot;);\r\nappend,prepend,after,before(이&nbsp;속에는&nbsp;무한정쓸&nbsp;수&nbsp;있다.)&nbsp;ex)&nbsp;$(&quot;body&quot;).append(&quot;text1&quot;,&quot;text2&quot;);\r\n\r\nJquery&nbsp;Remove&nbsp;Element\r\n$(&quot;p&quot;).remove();&nbsp;p태그삭제\r\n$(&quot;p&quot;).remove(&quot;.fw&quot;)&nbsp;p태그에서&nbsp;class=''fw''인&nbsp;것을&nbsp;삭제\r\n$(&quot;p&quot;).empty();&nbsp;p태그&nbsp;속을&nbsp;비움\r\n\r\nJquery&nbsp;CSS&nbsp;class\r\n$(&quot;p&quot;).addClass(&quot;fw&quot;);&nbsp;p태그에&nbsp;fw라는&nbsp;class를&nbsp;넣음\r\n$(&quot;p&quot;).addClass(&quot;fw&nbsp;ft11&quot;)&nbsp;p태그에&nbsp;fw,&nbsp;ft11라는&nbsp;class&nbsp;두개를&nbsp;넣음\r\n$(&quot;p&quot;).removeClass(&quot;fw&quot;)&nbsp;p태그에&nbsp;fw라는&nbsp;class를&nbsp;제거\r\n$(&quot;p&quot;).toggleClass(&quot;fw&quot;)&nbsp;add,remove\r\n\r\nJquery&nbsp;css()\r\n$(&quot;p&quot;).css(&quot;background-color&quot;)&nbsp;p태그의&nbsp;background-color속성을&nbsp;가져옴\r\n$(&quot;p&quot;).css(&quot;background-color&quot;,&quot;black&quot;);&nbsp;p태그에&nbsp;background-color:black을&nbsp;적용\r\n$(&quot;p&quot;).css({&quot;background-color&quot;:&quot;black&quot;,&quot;font-size&quot;:&quot;12px&quot;});\r\n\r\nJquery&nbsp;Dimension&nbsp;Method\r\nwidth()&nbsp;css로&nbsp;준&nbsp;가로,&nbsp;height()&nbsp;css로&nbsp;준&nbsp;세로\r\ninnerWidth()&nbsp;보이는&nbsp;안쪽&nbsp;가로,&nbsp;innerHeight()&nbsp;보이는&nbsp;안쪽&nbsp;세로\r\nouterWidth()&nbsp;보이는&nbsp;바깥쪽&nbsp;가로,outerHeight()&nbsp;보이는&nbsp;바깥쪽&nbsp;세로\r\nouterWidth(ture)&nbsp;margin까지&nbsp;포함한&nbsp;가로,outerHeight(ture)&nbsp;margin까지&nbsp;포함한&nbsp;세로', '2012-12-05 20:40:14', '2012-12-06 10:23:15', ''),
(64, 'Jquery Ajax', 'Jquery', '', 'Jquery&nbsp;load()&nbsp;Method\r\nload(URL,data,callback)\r\n$(&quot;#box&quot;).load(&quot;./test.php&quot;);&nbsp;test.php를&nbsp;읽어&nbsp;온다.\r\n$(&quot;#box&quot;).load(&quot;./test.php&nbsp;#box2&quot;);&nbsp;test.php&nbsp;안에&nbsp;있는&nbsp;것중에&nbsp;id=&quot;box&quot;인&nbsp;것을&nbsp;선택해서&nbsp;가져옴\r\n$(&quot;#box&quot;).load(&quot;./text.php&quot;,function(responseTxt,statusTxt,xhr){\r\n&nbsp;&nbsp;if(statusTxt&nbsp;==&nbsp;&quot;success&quot;){\r\n&nbsp;&nbsp;&nbsp;&nbsp;alert(&quot;success&quot;);\r\n&nbsp;&nbsp;}else&nbsp;if(statusTxt&nbsp;==&nbsp;&quot;error&quot;){\r\n&nbsp;&nbsp;&nbsp;&nbsp;alert(&quot;Error:&quot;+xhr.status+&quot;:&quot;.xhr.statusText);\r\n&nbsp;&nbsp;}\r\n});\r\n\r\nJquery&nbsp;$.get()&nbsp;and&nbsp;$.post()&nbsp;Method\r\n$.get(URL,callback);\r\n$.get(&quot;./test.php&quot;,function(data,status){\r\n\r\n});\r\n\r\n$.post(URL,data,callback)\r\n$.post(&quot;./test.php&quot;,\r\n&nbsp;&nbsp;{\r\n&nbsp;&nbsp;&nbsp;&nbsp;name:&quot;조용구&quot;,\r\n&nbsp;&nbsp;&nbsp;&nbsp;subject:&quot;제목&quot;\r\n&nbsp;&nbsp;},\r\n&nbsp;&nbsp;function(data,status){\r\n\r\n});', '2012-12-05 21:08:15', '2012-12-06 10:24:28', ''),
(65, 'Jquery Misc', 'Jquery', '', 'jquery다른 framework가 $를 셀렉터로 사용할 때 어떻게 해야 할까?? 그렇때 사용하는 것이다.\r\n$.noConflict(); 이것을 사용하면 $대신 jQuery를 사용하면된다.\r\n  jQuery(document).ready(function(){\r\n    jQuery(&quot;button&quot;).click(function(){\r\n      alert(&quot;야호&quot;);\r\n    });\r\n});\r\n\r\njQuery가 길다면 다른 걸로 지정할 수 있다.\r\nvar jq = $.noConflict();\r\njq(document).ready(function(){\r\n&nbsp;&nbsp;jq(&quot;button&quot;).click(function(){\r\n&nbsp;&nbsp;&nbsp;&nbsp;alert(&quot;야호&quot;);\r\n&nbsp;&nbsp;});\r\n});\r\n\r\n그래도 $를 사용하고 싶다면\r\n$.noConflict();\r\njQuery(document).ready(function($){\r\n  $(&quot;button&quot;).click(function(){\r\n    alert(&quot;야호 $사용할 수 있다.&quot;);\r\n  });\r\n});', '2012-12-05 21:15:25', '2012-12-06 10:23:50', ''),
(66, 'Interaction-Draggable', 'Jquery UI', '', '클릭해서 움직이게 할 수 있음\r\n$(&quot;#box&quot;).draggable();\r\n\r\n$(&quot;#box&quot;).draggable({\r\n    axis : &quot;x&quot; or &quot;y&quot; //움지는 방향을 정할 수 있음\r\n    cancel : &quot;id or class&quot; //지정하여 취소\r\n    containment : &quot;parent&quot;,&quot;document&quot;,&quot;window&quot; //영역을 지정함\r\n    cursor : &quot;커서 스타일을 정함&quot;\r\n    cursorAt : { left : , right : , top : , bottom : } // 커서의 위치를 정함\r\n    delay : milisecond 단위로 드래그 되는 시간을 지연시킨다.\r\n    disabled : true or false //드래그가 되는 것을 막음\r\n    distance : int 드래그를 시작하고 일정한 pixel단위로 마우스가 이동이되면 이동이 됨\r\n    grid : [ x, y ] //드래그 될때 한번씩 움직일 때 이동 거리\r\n&nbsp;&nbsp;&nbsp;&nbsp;opacity&nbsp;:&nbsp;between&nbsp;0&nbsp;and&nbsp;1\r\n});', '2012-12-05 21:36:40', '2012-12-06 12:15:31', ''),
(67, 'Interaction-Droppable', 'Jquery UI', '', '$(&quot;droppable&quot;).droppable({\r\n&nbsp;&nbsp;accept&nbsp;:&nbsp;&quot;#draggable&quot;,&nbsp;//어떤것만&nbsp;할&nbsp;건지&nbsp;정함\r\n&nbsp;&nbsp;activeClass&nbsp;:&nbsp;&quot;&quot;,\r\n&nbsp;&nbsp;hoverClass&nbsp;:&nbsp;&quot;&quot;,\r\n&nbsp;&nbsp;drop:function(event,ui){&nbsp;//drop이&nbsp;끝나면&nbsp;효과&nbsp;나옴\r\n&nbsp;&nbsp;}\r\n});', '2012-12-05 21:42:18', '2012-12-06 10:25:00', ''),
(68, 'Interaction-Resizable', 'Jquery UI', '', '$(&quot;#resizable&quot;).resizable(); //사이즈를 바꿀 수 있음', '2012-12-05 21:43:30', '2012-12-05 21:47:43', ''),
(69, 'Interaction-Selectable', 'Jquery UI', '', '$(&quot;#selectable&quot;).selectable(); //선택을 할 수 있음', '2012-12-05 21:46:13', '2012-12-05 21:47:38', ''),
(70, 'Interaction-Sortable', 'Jquery UI', '', '$(&quot;#selection&quot;).sortable();\r\n$(&quot;#selection&quot;).disableSelection();&nbsp;//이것을&nbsp;써줘야&nbsp;선택을&nbsp;할&nbsp;수&nbsp;있다.\r\n\r\n$(&quot;#selection&quot;).sortable({\r\n&nbsp;&nbsp;connectWith:&quot;.sortable&quot;&nbsp;//class가&nbsp;sortable인&nbsp;것끼리&nbsp;옮겨&nbsp;다닐&nbsp;수&nbsp;있다.\r\n}).disableSelection();', '2012-12-05 21:51:34', '2012-12-06 10:24:47', ''),
(72, 'js 직접쓸 때 validation 안걸리기', 'other', '', '//&lt;![CDATA[\r\n//]]&gt;\r\n\r\nCDATA를 쓰면 validation에 걸리지 않음', '2012-12-06 09:52:00', '2012-12-06 09:55:33', ''),
(73, 'Jquery and Jquery UI setting', 'other', '', 'Jquery UI는 Jquery를 이용하여 만들어 진것이기때문에 jquery set 후 jquery ui set 하기', '2012-12-06 09:58:04', '2012-12-06 09:58:10', ''),
(75, '새롭게 안것', 'other', '', 'a&nbsp;태그에&nbsp;javascript&nbsp;를&nbsp;정확히&nbsp;쓰고&nbsp;싶으면\r\nhref=''javascript:return&nbsp;false;''&nbsp;를&nbsp;쓴다.\r\n\r\n게시판&nbsp;글에&nbsp;공백을&nbsp;넣어&nbsp;주고&nbsp;싶다면\r\n$content&nbsp;=&nbsp;preg_replae(&quot;/[[:space:]]/&quot;,&quot;&amp;nbsp;&quot;,$content);\r\n글을&nbsp;넣을&nbsp;때&nbsp;공백을&nbsp;&amp;nbsp;로&nbsp;바꿔&nbsp;주어야&nbsp;한다.', '2012-12-06 10:43:32', '0000-00-00 00:00:00', ''),
(76, '현제 로딩된 기계의 정보가져 오기', 'other', '', '$_SERVER[''HTTP_USER_AGENT'']&nbsp;이렇게&nbsp;사용하면&nbsp;사용자의&nbsp;기계정보를&nbsp;가져&nbsp;올&nbsp;수&nbsp;있다.', '2012-12-06 12:21:34', '0000-00-00 00:00:00', ''),
(77, 'Progressbar', 'Jquery UI', 'Widgets', '$(&quot;#bar&quot;).progressbar({value : 20}); //빈영역에서 value %만큼 영역이 체워짐', '2012-12-06 13:12:49', '2012-12-06 13:13:26', ''),
(79, 'Jquery Mobile Start', 'Jquery Mobile', '', '&lt;!DOCTYPE html&gt;\r\n&lt;html&gt;\r\n    &lt;head&gt;\r\n    &lt;/head&gt;\r\n    &lt;body&gt;\r\n    &lt;/body&gt;\r\n&lt;/html&gt;\r\n&lt;/html&gt;\r\n\r\nDOCTYPE은 HTML5용을 타이핑한다.\r\n\r\n\r\n &lt;link rel=&quot;stylesheet&quot; href=&quot;http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css&quot; /&gt;\r\n &lt;script src=&quot;http://code.jquery.com/jquery-1.8.2.min.js&quot;&gt;&lt;/script&gt;\r\n &lt;script src=&quot;http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js&quot;&gt;&lt;/script&gt;\r\n\r\nMobile용으로 CSS와 jQuery를 포함시킨다.\r\n\r\n&lt;meta&nbsp;name=&quot;viewport&quot;&nbsp;content=&quot;width=device-width,&nbsp;initial-scale=1&quot;&gt;\r\n이것을&nbsp;써주면&nbsp;Device의&nbsp;크기대로&nbsp;정확히&nbsp;됨', '2012-12-06 14:29:46', '2012-12-06 14:36:00', ''),
(80, '기본 타이핑', 'Jquery Mobile', '', '&lt;div data-role=&quot;page&quot;&gt; //가장 겉부분에 감싼다.\r\n    &lt;div data-role=&quot;header&quot;&gt;\r\n         &lt;h1&gt;data-role=&quot;header&quot;로 지정하면 기본적으로 스타일이 적용됨&lt;/h1&gt;\r\n    &lt;/div&gt;\r\n    &lt;div data-role=&quot;content&quot;&gt;\r\n        &lt;p&gt;data-role=&quot;content&quot;는 콘텐츠 부분을 뜻한다.&lt;/p&gt;\r\n    &lt;/div&gt;\r\n    &lt;ul data-role=&quot;listview&quot; data-filter=&quot;true&quot;&gt; //data-role=&quot;listview&quot;는 리스트 형식으로 보여줌 data-filter=&quot;true&quot;로 하면 검색을 할 수 있음\r\n        &lt;li&gt;리스트1&lt;/li&gt;\r\n        &lt;li&gt;리스트2&lt;/li&gt;\r\n        &lt;li&gt;&lt;a href=&quot;#&quot;&gt;여기에 a까지 하면 다르게 보임&lt;/a&gt;&lt;/li&gt;\r\n    &lt;/ul&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;div&nbsp;data-role=&quot;footer&quot;&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;h4&gt;Footer&lt;/h4&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div&gt;\r\n&lt;/div&gt;\r\n\r\n버튼을 만들고 싶다면\r\ndata-role=&quot;button&quot;을 써 주면 된다.\r\ndata-theme=&quot;a ~ z&quot; 버튼 스타일을 줄 수 있음\r\ndata-icon=''star'' 버튼에 아이콘을 넣어 줄수 있다.', '2012-12-06 14:35:34', '2012-12-06 14:47:14', ''),
(81, 'data-role=&quot;page&quot; 로 지정후 페이지 이동하기', 'Jquery Mobile', '', '&lt;div&nbsp;data-role=&quot;page&quot;&nbsp;id=&quot;foo&quot;&gt;\r\n&nbsp;&lt;div&nbsp;data-role=&quot;header&quot;&gt;\r\n&nbsp;&nbsp;&lt;h1&gt;HEADER&lt;/h1&gt;\r\n&nbsp;&lt;/div&gt;\r\n&nbsp;&lt;div&nbsp;data-role=&quot;content&quot;&gt;\r\n&nbsp;&nbsp;&lt;p&gt;&lt;a&nbsp;href=&quot;#bar&quot;&gt;CONTENT&lt;/a&gt;&lt;/p&gt;\r\n&nbsp;&lt;/div&gt;\r\n&nbsp;&lt;div&nbsp;data-role=&quot;footer&quot;&gt;\r\n&nbsp;&nbsp;&lt;h4&gt;FOOTER&lt;/h4&gt;\r\n&nbsp;&lt;/div&gt;\r\n&lt;/div&gt;\r\n&lt;div&nbsp;data-role=&quot;page&quot;&nbsp;id=&quot;bar&quot;&gt;\r\n&nbsp;&lt;div&nbsp;data-role=&quot;header&quot;&gt;\r\n&nbsp;&nbsp;&lt;h1&gt;HEADER&lt;/h1&gt;\r\n&nbsp;&lt;/div&gt;\r\n&nbsp;&lt;div&nbsp;data-role=&quot;content&quot;&gt;\r\n&nbsp;&nbsp;&lt;p&gt;&lt;a&nbsp;href=&quot;#foo&quot;&gt;CONTENT&lt;/a&gt;&lt;/p&gt;\r\n&nbsp;&lt;/div&gt;\r\n&nbsp;&lt;div&nbsp;data-role=&quot;footer&quot;&gt;\r\n&nbsp;&nbsp;&lt;h4&gt;FOOTER&lt;/h4&gt;\r\n&nbsp;&lt;/div&gt;\r\n&lt;/div&gt;\r\n\r\n이런식으로&nbsp;지정하면&nbsp;href=&quot;#foo&quot;&nbsp;를&nbsp;누르면&nbsp;id=&quot;foo&quot;가&nbsp;나타난다.', '2012-12-06 14:55:20', '0000-00-00 00:00:00', ''),
(82, 'a 링크 이동하기', 'Jquery Mobile', '', '&lt;a&nbsp;href=&quot;경로&quot;&gt;이동&lt;/a&gt;&nbsp;이런&nbsp;방식으로&nbsp;사용하면&nbsp;페이지&nbsp;로딩없이&nbsp;이동이&nbsp;된다.\r\n하지만&nbsp;rel=&quot;external&quot;&nbsp;를&nbsp;써&nbsp;주게&nbsp;되면&nbsp;로딩있이&nbsp;이동이&nbsp;된다.', '2012-12-06 15:11:25', '0000-00-00 00:00:00', ''),
(83, 'Page Transitions', 'Jquery Mobile', '', '&lt;a&nbsp;href=&quot;&quot;&nbsp;data-transition=&quot;&quot;&gt;&lt;/a&gt;\r\ndata-transition&nbsp;=&nbsp;\r\nfade\r\npop\r\nflip&nbsp;:&nbsp;돌아가면서\r\nturn&nbsp;:&nbsp;flip과&nbsp;비슷하지만&nbsp;방향이&nbsp;다름\r\nflow&nbsp;:&nbsp;작아졌다&nbsp;커짐\r\n그외&nbsp;slidefade,&nbsp;slide,&nbsp;slideup&nbsp;slidedown', '2012-12-06 15:18:16', '0000-00-00 00:00:00', ''),
(84, 'Page Loading', 'Jquery Mobile', '', '$.mobile.loading(''show'',{\r\n&nbsp;&nbsp;&nbsp;&nbsp;theme&nbsp;:&nbsp;&quot;a&quot;,\r\n&nbsp;&nbsp;&nbsp;&nbsp;textonly&nbsp;:&nbsp;true\r\n});\r\n\r\n$.mobile.changePage()', '2012-12-06 15:28:43', '0000-00-00 00:00:00', ''),
(85, 'Dialog or Popup', 'Jquery Mobile', '', '&lt;a href=&quot;/mobilepage/index2.php&quot; class=&quot;selector&quot; data-rel=&quot;dialog&quot;&gt;open&lt;/a&gt;\r\n이렇게 사용하면 페이지가 상자로 나옴\r\n\r\n&lt;a&nbsp;href=&quot;#txt&quot;&nbsp;data-rel=&quot;popup&quot;&gt;OPEN&lt;/a&gt;\r\n&lt;div&nbsp;id=&quot;txt&quot;&nbsp;data-role=&quot;popup&quot;&gt;팝업입니다.&lt;/div&gt;', '2012-12-06 15:35:37', '2012-12-06 15:39:36', ''),
(86, 'Theme Change', 'Jquery Mobile', '', '&lt;div&nbsp;data-role=&quot;header&quot;&nbsp;data-theme=&quot;d&quot;&gt;&nbsp;data-theme를&nbsp;써주면&nbsp;된다.\r\n&lt;/div&gt;', '2012-12-06 15:44:25', '0000-00-00 00:00:00', ''),
(87, 'Button Or Data-Icon 종류', 'Jquery Mobile', '', 'delete, check, plus,&nbsp;minus,&nbsp;refresh\r\nforward&nbsp;:&nbsp;앞으로&nbsp;화살표\r\nback&nbsp;:&nbsp;뒤로&nbsp;화살표\r\nalert&nbsp;:&nbsp;경고\r\ninfo,&nbsp;home,&nbsp;search\r\ngear : 기어모양\r\narrow-u,arrow-d,arrow-l,arrow-r : 화살표 위, 아래,&nbsp;왼쪽,&nbsp;오른쪽\r\n\r\n아이콘 위치\r\ndata-iconpos= top, bottom, left, right\r\n\r\ndata-mini = &quot;true&quot; 버튼이 더 잘아 보인다.\r\n\r\ndata-inline&nbsp;=&nbsp;&quot;true&quot;&nbsp;버튼을&nbsp;한줄로\r\n\r\ndata-role&nbsp;=&nbsp;&quot;controlgroup&quot;&nbsp;버튼을&nbsp;그룹으로&nbsp;묶음\r\n그후\r\ndata-type&nbsp;=&nbsp;&quot;horizontal&quot;를&nbsp;사용하면&nbsp;할&nbsp;줄로&nbsp;묶는&nbsp;다.', '2012-12-06 15:52:28', '2012-12-06 16:09:18', ''),
(88, 'Toolbars', 'Jquery Mobile', '', '&lt;div&nbsp;data-role=&quot;navbar&quot;&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;ul&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;&lt;a&nbsp;href=&quot;&quot;&gt;첫번째&lt;/a&gt;&lt;/li&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;&lt;a&nbsp;href=&quot;&quot;&gt;첫번째&lt;/a&gt;&lt;/li&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;&lt;a&nbsp;href=&quot;&quot;&gt;첫번째&lt;/a&gt;&lt;/li&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;&lt;a&nbsp;href=&quot;&quot;&gt;첫번째&lt;/a&gt;&lt;/li&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;/ul&gt;\r\n&lt;/div&gt;\r\n\r\ndata-role=&quot;navbar&quot;를&nbsp;주고&nbsp;a&nbsp;까지&nbsp;써줘야&nbsp;정확히&nbsp;나온다.\r\n5개까지는&nbsp;한줄로&nbsp;나오지만&nbsp;6개&nbsp;부터는&nbsp;한줄에&nbsp;2개씩&nbsp;출력된다.', '2012-12-06 15:57:48', '0000-00-00 00:00:00', ''),
(89, '위치 고정시키기', 'Jquery Mobile', '', 'data-position=&quot;fixed&quot;&nbsp;이렇게&nbsp;사용하면&nbsp;고정이&nbsp;된다.', '2012-12-06 16:00:53', '0000-00-00 00:00:00', ''),
(90, 'Collapsible', 'Jquery Mobile', '', '&lt;div&nbsp;data-role=&quot;collapsible&quot;&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;h1&gt;I''m&nbsp;a&nbsp;header&lt;/h1&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;아래에&nbsp;있는&nbsp;것은&nbsp;숨겨집니다.\r\n&lt;/div&gt;\r\n\r\n위처럼하면&nbsp;&lt;h1&gt;태그&nbsp;아래&nbsp;것은&nbsp;기본적으로&nbsp;숨겨져있다.\r\n하지만&nbsp;그렇게&nbsp;하지않고&nbsp;기본적으로&nbsp;보이고&nbsp;싶다면\r\n&lt;div&nbsp;data-role=&quot;collapsible&quot;&nbsp;data-collapsed=&quot;false&quot;&gt;을&nbsp;해주면&nbsp;된다.', '2012-12-06 16:19:43', '0000-00-00 00:00:00', ''),
(91, 'HTML5 Start', 'HTML5', '', '&lt;!DOCTYPE&nbsp;html&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;head&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;/head&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;body&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;/body&gt;\r\n&lt;/html&gt;', '2012-12-07 14:11:55', '0000-00-00 00:00:00', ''),
(92, '&lt;base&gt; Tag', 'HTML5', '', '&lt;head&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;base&nbsp;href=&quot;&quot;&nbsp;/&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;base&nbsp;target=&quot;&quot;&nbsp;/&gt;\r\n&lt;/head&gt;\r\n\r\na&nbsp;태그의&nbsp;기본&nbsp;href과&nbsp;target을&nbsp;정함', '2012-12-07 14:13:03', '0000-00-00 00:00:00', ''),
(93, 'Table', 'HTML5', '', '&lt;table border=&quot;1&quot;&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;caption&gt;테이블 설명&lt;/caption&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;colgroup&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;col style=&quot;width:100px&quot; /&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;col /&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp; &lt;/colgroup&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp; &lt;thead&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;tr&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   &lt;th&gt;th입니다.&lt;/th&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   &lt;th&gt;그리고 thead를 어디에 두어도 위에 출력됩니다.&lt;/th&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/tr&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/thead&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp; &lt;tbody&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &lt;tr&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   &lt;td&gt;td입니다.&lt;/td&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   &lt;td&gt;td입니다.&lt;/td&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &lt;/tr&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp; &lt;/tbody&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp; &lt;tfoot&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &lt;tr&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   &lt;td&gt;tfoot을 어디에 두어도 아래로 출력됨니다.&lt;/td&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &lt;/tr&gt;\r\n&nbsp;&nbsp;&nbsp; &lt;/tfoot&gt;\r\n&lt;/table&gt;', '2012-12-07 14:19:43', '2012-12-07 14:21:00', ''),
(94, 'Lists', 'HTML5', '', '&lt;ul&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;Unordered&nbsp;Lists&lt;/li&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;Unordered&nbsp;Lists&lt;/li&gt;\r\n&lt;/ul&gt;\r\n\r\n&lt;ol&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;Ordered&nbsp;Lists&lt;/li&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;Ordered&nbsp;Lists&lt;/li&gt;\r\n&lt;/ol&gt;\r\n\r\n&lt;dl&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;dt&gt;dl&nbsp;태그란&lt;/dt&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;dd&gt;Definition&nbsp;Lists&nbsp;로&nbsp;정의를&nbsp;할&nbsp;때&nbsp;사용한다.&lt;/dd&gt;\r\n&lt;/dl&gt;', '2012-12-07 14:28:13', '0000-00-00 00:00:00', ''),
(95, 'Video and Audio', 'HTML5', '', '&lt;video width=&quot;100&quot; height=&quot;100&quot; controls&gt;\r\n     &lt;source src=&quot;movie.mp4&quot; type=&quot;video/mp4&quot; /&gt;\r\n     &lt;source src=&quot;movie.ogg&quot; type=&quot;video/ogg&quot; /&gt;\r\n      video를 지원하지 않습니다.\r\n&lt;/video&gt;\r\n\r\n&lt;audio contros&gt;\r\n     &lt;source src=&quot;horse.ogg&quot; type=&quot;audio/ogg&quot; /&gt;\r\n     &lt;source src=&quot;horse.mp3&quot; type=&quot;audio/mpeg&quot; /&gt;\r\n     Audio를 지원하지 않습니다.\r\n&lt;/audio&gt;', '2012-12-07 14:45:03', '2012-12-07 14:48:52', ''),
(96, 'New Input', 'HTML5', '', '&lt;input type=&quot;color&quot; /&gt; //color picker\r\n\r\n&lt;input type=&quot;date&quot; /&gt; //selectable date\r\n\r\n&lt;input type=&quot;datetime&quot; /&gt;//selectable date or time\r\n\r\n&lt;input type=&quot;datatime-local&quot; /&gt; //like datetime\r\n\r\n&lt;input type=&quot;email&quot; /&gt; //email전용 자동으로 validation\r\n\r\n&lt;input type=&quot;month&quot; /&gt; //month 와 year 을 선택\r\n\r\n&lt;input type=&quot;number&quot; min=&quot;0&quot; max=&quot;5&quot; /&gt; // 숫자를 선택할 수 있음\r\n\r\n&lt;input type=&quot;range&quot; min=&quot;0&quot; max=&quot;5&quot; /&gt; //slider control이 나와서 선택할 수 있음\r\n\r\n&lt;input type=&quot;search&quot; /&gt; //검색 필드\r\n\r\n&lt;input type=&quot;tel&quot; /&gt; //전화번호 전용\r\n\r\n&lt;input type=&quot;time&quot; /&gt; //시간을 선택할 수 있음\r\n\r\n&lt;input type=&quot;week&quot; /&gt; //주를 선택\r\n\r\n&lt;input type=&quot;url&quot; /&gt; //입력하면 http://까지 나옴', '2012-12-07 15:01:59', '0000-00-00 00:00:00', ''),
(97, 'Form Elements', 'HTML5', '', '&lt;input&nbsp;list=&quot;browsers&quot;&nbsp;/&gt;\r\n\r\n&lt;datalist&nbsp;id=&quot;browsers&quot;&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;option&nbsp;value=&quot;IE&quot;&nbsp;/&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;option&nbsp;value=&quot;FF&quot;&nbsp;/&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;option&nbsp;value=&quot;Chrome&quot;&nbsp;/&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;option&nbsp;value=&quot;Opera&quot;&nbsp;/&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;option&nbsp;value=&quot;Safari&quot;&nbsp;/&gt;\r\n&lt;/datalist&gt;\r\n\r\n자동완성&nbsp;기능을&nbsp;가짐\r\n\r\n&lt;form&nbsp;oninput=&quot;x.value=parseInt(a.value)+parseInt(b.value)&quot;&gt;0\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;input&nbsp;type=&quot;range&quot;&nbsp;name=&quot;a&quot;&nbsp;value=&quot;50&quot;&gt;100&nbsp;&nbsp;+\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;input&nbsp;type=&quot;number&quot;&nbsp;name=&quot;b&quot;&nbsp;value=&quot;50&quot;&gt;=\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;output&nbsp;name=&quot;x&quot;&nbsp;for=&quot;a&nbsp;b&quot;&gt;&lt;/output&gt;\r\n&lt;/form&gt;\r\n\r\n값을&nbsp;변경하면&nbsp;바로&nbsp;같이&nbsp;추출&nbsp;된다.', '2012-12-07 15:09:57', '0000-00-00 00:00:00', ''),
(99, 'Form Attribute', 'HTML5', '', '&lt;input&nbsp;type=&quot;text&quot;&nbsp;autofocus&nbsp;/&gt;&nbsp;//자동&nbsp;포커스를&nbsp;가짐\r\n\r\n&lt;input&nbsp;type=&quot;text&quot;&nbsp;form=&quot;frm&quot;&nbsp;/&gt;&nbsp;//&nbsp;form&nbsp;속에&nbsp;있지&nbsp;않아도&nbsp;전송이&nbsp;됨\r\n\r\n&lt;input&nbsp;type=&quot;submit&quot;&nbsp;formaction=&quot;&quot;&nbsp;/&gt;&nbsp;//form&nbsp;action을&nbsp;바꿀&nbsp;수&nbsp;있다.\r\n\r\n&lt;input&nbsp;type=&quot;submit&quot;&nbsp;formenctype=&quot;&quot;&nbsp;/&gt;&nbsp;//form&nbsp;enctype을&nbsp;바꿀&nbsp;수&nbsp;있다.\r\n\r\n&lt;input&nbsp;type=&quot;submit&quot;&nbsp;formmethod=&quot;&quot;&nbsp;/&gt;&nbsp;//form&nbsp;method를&nbsp;바꿀&nbsp;수&nbsp;있다.\r\n\r\n&lt;input&nbsp;type=&quot;file&quot;&nbsp;multiple&nbsp;/&gt;&nbsp;//파일을&nbsp;다중으로&nbsp;선택할&nbsp;수&nbsp;있다.\r\n\r\n&lt;input&nbsp;type=&quot;text&quot;&nbsp;placeholder=&quot;기본값&quot;&nbsp;/&gt;&nbsp;//기본값을&nbsp;지정할&nbsp;수&nbsp;있다.\r\n\r\n&lt;input&nbsp;type=&quot;number&quot;&nbsp;name=&quot;points&quot;&nbsp;step=&quot;3&quot;&nbsp;/&gt;&nbsp;//증가값을&nbsp;지정할&nbsp;수&nbsp;있다.', '2012-12-07 15:24:30', '0000-00-00 00:00:00', ''),
(108, '공부했던 함수', 'other', '', 'fgetcsv(handle, length, delimiter);\r\n\r\nstr_repeat(str, len);\r\n\r\n$ext = end(explode(delimiter, string)); // end() 배열에 가장 마지막 것을 가져옴\r\n\r\nstr_pad(str, len, pad_str, STR_PAD_LEFT);\r\n\r\ncheckdate(month, day, year);\r\n\r\nextract(); 배열 key를 변수명으로 바꿔줌\r\nconpact(); //extract의 반대\r\n$name = &quot;조용구&quot;; $address = &quot;여수&quot;;\r\n$arr = compact(&quot;name&quot;,&quot;address&quot;);\r\nprint_r($arr); // Array([name]=&gt;&quot;조용구&quot;,[address]=&gt;&quot;여수&quot;);\r\n\r\nInjection 대비코드\r\n\r\n$row = fetch(&quot;select * from member where id=''$id''&quot;);\r\nif($row){\r\n    if($pwd = $row[''pwd'']){\r\n        Login 확인\r\n    }\r\n}\r\n\r\n이렇게 하면 pwd를 입력할 수 밖에 없다.\r\n\r\neach(arr); // 변수속에 key, value를 배열로 준다. ex) $arr = each(arr); $arr[''key''], $arr[''value''];\r\n\r\nlist(val1, val2,.....) = $arr //배여레 있는 value를 변수로 저장해줌\r\n\r\n$arr = array(&quot;b&quot;=&gt;1000, &quot;a&quot;=&gt;10000,&quot;c&quot;=&gt;1200);\r\n\r\nsort() =&gt; [0]=&gt;1000, [1]=&gt;1200, [2]=&gt;10000  &lt;=&gt;  rsort();\r\nasort() =&gt; [b]=&gt;1000, [c]=&gt;1200, [a]=&gt;10000   &lt;=&gt;  arsort();\r\nksort() =&gt; [a]=&gt;10000, [b]=&gt;1000, [c]=&gt;1200   &lt;=&gt;   krsort();\r\n\r\nshuffle(arr); // 배열을 섞음\r\n\r\nnatsort($arr); //자연순 알고리즘 정렬\r\narray_pop($arr); 마지막 값을 가져오고 배열에서 삭제 &lt;=&gt; array_shift(); //앞에서 가져옴\r\narray_push($arr,val1,val2, ...); //array속에 value를 끝에서 부터 &lt;=&gt; array_unshift(); //앞에 넣어줌\r\n\r\nstrtr(str, from str, to str);\r\n\r\nctype_digit(); //숫자체크\r\nctype_alpha(); //알파벳 문자 체크\r\nctype_alnum(); //영, 숫자 체크\r\n\r\nrange(start,end);// 증가하는 문자나 숫자를 배열로 넣고 싶을 때\r\n\r\nchunk_split(str, len, del); //str을 len만큼 del 로 끊어서 반환\r\n\r\narray_sum(arr); //배열에 있는 값을 더해준다.\r\narray_merge(arr1, arr2, ...); //배열을 합친다.\r\narray_flip($arr); //key와 value를 교체\r\n\r\nbase_convert(num, now 진법, 변환할 진법);\r\n\r\ndecbin 10 -&gt; 2   decoct 10 -&gt; 8  dechex 10 -&gt; 16\r\nbindec 2 -&gt; 10  octdec 8 -&gt; 10 hexdec 16 -&gt; 10\r\n\r\n8진수 문자 3개 \\100로 표현', '2012-12-08 09:47:14', '2012-12-08 09:47:27', ''),
(109, '직접 script 쓰때 CDATA', 'other', '', 'CDATA\r\n\r\n//&lt;![[CDATA[\r\n//]]&gt;', '2012-12-08 09:48:29', '0000-00-00 00:00:00', ''),
(110, '엑셀파일 만들기', 'other', '', '&lt;?php\r\n//GET&nbsp;값을&nbsp;urlencode()로&nbsp;보낸&nbsp;뒤\r\n\r\n$wfile&nbsp;=&nbsp;urldecode($_GET[''wfile'']);\r\n$wfile_name&nbsp;=&nbsp;urldecode($_GET[''wfile_name'']);\r\n\r\nheader(''Content-Type:application/octet-stream'');\r\nheader(''Content-Length:''.filesize($wfile));\r\nheader(''Content-Disposition:attachment;&nbsp;filename=''.$wfile_name);\r\nheader(''Content-Transfer-Encoding:Binary'');\r\n\r\n-------------------------\r\n|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|\r\n|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Table&nbsp;내용&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|\r\n|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|\r\n-------------------------\r\n\r\n$fp&nbsp;=&nbsp;fopen($wfile,&quot;r&quot;);\r\nfpassthru($fp);\r\nfclose($fp);\r\n?&gt;', '2012-12-08 09:52:43', '0000-00-00 00:00:00', ''),
(111, 'PHP 파일함수', 'other', '', '$fp&nbsp;=&nbsp;fopen();\r\n$data&nbsp;=&nbsp;fgets($fp);\r\necho&nbsp;$data;\r\n$data&nbsp;=&nbsp;fgets($fp);\r\necho&nbsp;$data;\r\n두&nbsp;개의&nbsp;값이&nbsp;다르게&nbsp;나온다.&nbsp;파일포인터가&nbsp;바뀌기&nbsp;때문이다.\r\n\r\nfseek(handle,&nbsp;which);&nbsp;//포인터의&nbsp;위치를&nbsp;바꿔줌\r\n\r\ntmpfile&nbsp;create\r\n\r\n$temp&nbsp;=&nbsp;tmpfile();\r\nfwrite($temp,&quot;write&quot;);\r\nfseek($temp,0);\r\necho&nbsp;fread($temp,1024);\r\nfclose($temp);\r\n//초기에&nbsp;파일&nbsp;포인터는&nbsp;글의&nbsp;길이&nbsp;만큼&nbsp;위치함\r\n\r\nftell();&nbsp;파일&nbsp;포인터&nbsp;위치를&nbsp;반환\r\nfeof();&nbsp;파일포인터가&nbsp;끝이면&nbsp;false&nbsp;아니면&nbsp;true', '2012-12-08 10:43:24', '0000-00-00 00:00:00', ''),
(112, 'SQL 함수 DATE 및 Mysql 함수', 'other', '', 'date_format(wdate, ''%d/%m/%y'') as wdate\r\n\r\nmysql_result()&nbsp;하나의&nbsp;셀을&nbsp;반환\r\nmysql_fetch_array()&nbsp;다수를&nbsp;반환\r\n\r\nDB&nbsp;특정&nbsp;field&nbsp;명과&nbsp;field&nbsp;type&nbsp;가져오기\r\n\r\nwhile($row&nbsp;=&nbsp;mysql_fetch_field($res)){\r\n&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;$row&nbsp;-&gt;&nbsp;name;\r\n&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;$row&nbsp;-&gt;&nbsp;type;\r\n}', '2012-12-08 10:46:20', '2012-12-08 10:49:44', ''),
(113, 'Javascript 다중 배열 및 for in 문', 'other', '', 'var&nbsp;arr&nbsp;=&nbsp;{&nbsp;&quot;name&quot;&nbsp;:&nbsp;&quot;조용구&quot;,&nbsp;&quot;subject&quot;&nbsp;:&nbsp;&quot;제목&quot;&nbsp;}\r\nfor(key&nbsp;in&nbsp;arr){\r\n&nbsp;&nbsp;&nbsp;&nbsp;document,write(key+&quot;의&nbsp;값은&quot;+arr[key]+&quot;입니다.&quot;);\r\n}', '2012-12-08 10:47:55', '0000-00-00 00:00:00', ''),
(114, '빈값정확히 체크', 'other', '', 'empty는&nbsp;0을&nbsp;비웠다면&nbsp;함\r\n\r\n그렇기&nbsp;때문에\r\nif(isset($name)){\r\n&nbsp;&nbsp;&nbsp;&nbsp;if($name&nbsp;==&nbsp;&quot;&quot;){\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;&quot;비워져있음&quot;;\r\n&nbsp;&nbsp;&nbsp;&nbsp;}\r\n}', '2012-12-08 10:51:09', '2012-12-08 10:52:32', ''),
(115, '파일업로드 정확히 알기', 'other', '', '업로드&nbsp;사이즈는&nbsp;php.ini로&nbsp;지정이&nbsp;되어&nbsp;있다.\r\npost_max_size&nbsp;와&nbsp;upload_max_filesize\r\n\r\nphp.ini&nbsp;직접&nbsp;수정&nbsp;필요없이\r\nini_set(''post_max_size'',''30M'');\r\nini_set(''upload_max_filesize'',''30M'');\r\n\r\n하지만&nbsp;ini_set이&nbsp;안될&nbsp;때가&nbsp;있다.&nbsp;그럴&nbsp;때는&nbsp;.htaccess에서&nbsp;설정하면&nbsp;된다.\r\n\r\nphp_value&nbsp;upload_max_filesize&nbsp;1M\r\nphp_value&nbsp;post_max_size&nbsp;1M\r\n\r\n#참고\r\nphp_value&nbsp;max_execution_time&nbsp;300\r\nphp_value&nbsp;max_input_time&nbsp;300', '2012-12-08 10:57:29', '0000-00-00 00:00:00', ''),
(116, '보안', 'other', '', '스푸핑(spoofing)&nbsp;:&nbsp;''속이다''&nbsp;라는&nbsp;뜻으로&nbsp;값을&nbsp;속여서&nbsp;보낼때&nbsp;사용하는&nbsp;용어\r\nex)&nbsp;form&nbsp;spoofing,&nbsp;HTTP&nbsp;spoofing\r\n\r\nLogin&nbsp;몇번&nbsp;실패시&nbsp;로그인&nbsp;제한\r\n\r\nFile&nbsp;size&nbsp;limit\r\n$_FILES[''wfile''][''size'']로&nbsp;가져오고\r\n1024&nbsp;*&nbsp;1024&nbsp;(1MB)&nbsp;로&nbsp;나눠서&nbsp;8M(원하는&nbsp;사이즈)를&nbsp;체크&nbsp;후&nbsp;upload&nbsp;제한\r\n\r\n접근&nbsp;방어\r\n1.&nbsp;lv&nbsp;check\r\n2.&nbsp;IN_SIZE&nbsp;상수&nbsp;사용\r\n3.&nbsp;token&nbsp;check&nbsp;사용\r\n4.&nbsp;captcha&nbsp;사용', '2012-12-08 11:02:49', '0000-00-00 00:00:00', ''),
(117, 'Borders', 'CSS3', '', 'div\r\n{\r\n&nbsp;&nbsp;&nbsp;&nbsp;border:solid&nbsp;2px;\r\n&nbsp;&nbsp;&nbsp;&nbsp;border-radius&nbsp;:&nbsp;25px;&nbsp;//라운드&nbsp;생김\r\n&nbsp;&nbsp;&nbsp;&nbsp;-moz-border-radius:25px;&nbsp;/*&nbsp;Old&nbsp;FF&nbsp;*/\r\n\r\n&nbsp;&nbsp;&nbsp;&nbsp;box-shadow&nbsp;:&nbsp;x-px&nbsp;y-px&nbsp;blur-px&nbsp;color;\r\n}', '2012-12-08 14:07:47', '0000-00-00 00:00:00', ''),
(118, 'Background', 'CSS3', '', 'div\r\n{\r\n    background:url();\r\n    -moz-background-size:80px 60px /* Old FF */\r\n    background-size:80px 60px;\r\n    background-repeat:no-repeat;\r\n\r\n&nbsp;&nbsp;&nbsp;&nbsp;background-origin:border-box,&nbsp;padding-box,&nbsp;content-box;&nbsp;//background&nbsp;위치\r\n}\r\n\r\n', '2012-12-08 14:10:03', '2012-12-08 14:56:34', ''),
(119, 'Text Effects', 'CSS3', '', 'h1\r\n{\r\n&nbsp;&nbsp;&nbsp;&nbsp;text-shadow&nbsp;:&nbsp;x-px&nbsp;y-px&nbsp;blur-xp&nbsp;color;\r\n\r\n&nbsp;&nbsp;&nbsp;&nbsp;text-overflow:clip,&nbsp;ellipsis,&nbsp;string;\r\n\r\n&nbsp;&nbsp;&nbsp;&nbsp;\r\n}', '2012-12-08 15:04:07', '0000-00-00 00:00:00', ''),
(120, '2D Transform', 'Jquery', '', 'div\r\n{&nbsp;//시계방향으로&nbsp;돌아감\r\n&nbsp;&nbsp;&nbsp;&nbsp;transform:&nbsp;rotate(30deg);\r\n&nbsp;&nbsp;&nbsp;&nbsp;-ms-transform:&nbsp;rotate(30deg);&nbsp;/*&nbsp;IE&nbsp;9&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;&nbsp;-webkit-transform:&nbsp;rotate(30deg);&nbsp;/*&nbsp;Safari&nbsp;and&nbsp;Chrome&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;&nbsp;-o-transform:&nbsp;rotate(30deg);&nbsp;/*&nbsp;Opera&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;&nbsp;-moz-transform:&nbsp;rotate(30deg);&nbsp;/*&nbsp;Firefox&nbsp;*/\r\n}\r\n\r\ndiv\r\n{&nbsp;&nbsp;&nbsp;&nbsp;//현재위치에서&nbsp;움직임\r\n&nbsp;&nbsp;&nbsp;&nbsp;transform:&nbsp;translate(50px,100px);\r\n&nbsp;&nbsp;&nbsp;&nbsp;-ms-transform:&nbsp;translate(50px,100px);&nbsp;/*&nbsp;IE&nbsp;9&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;&nbsp;-webkit-transform:&nbsp;translate(50px,100px);&nbsp;/*&nbsp;Safari&nbsp;and&nbsp;Chrome&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;&nbsp;-o-transform:&nbsp;translate(50px,100px);&nbsp;/*&nbsp;Opera&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;&nbsp;-moz-transform:&nbsp;translate(50px,100px);&nbsp;/*&nbsp;Firefox&nbsp;*/\r\n}\r\n\r\ndiv\r\n{&nbsp;//스케일을&nbsp;바꿈\r\n&nbsp;&nbsp;&nbsp;&nbsp;transform:&nbsp;scale(2,4);\r\n&nbsp;&nbsp;&nbsp;&nbsp;-ms-transform:&nbsp;scale(2,4);&nbsp;/*&nbsp;IE&nbsp;9&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;&nbsp;-webkit-transform:&nbsp;scale(2,4);&nbsp;/*&nbsp;Safari&nbsp;and&nbsp;Chrome&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;&nbsp;-o-transform:&nbsp;scale(2,4);&nbsp;/*&nbsp;Opera&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;&nbsp;-moz-transform:&nbsp;scale(2,4);&nbsp;/*&nbsp;Firefox&nbsp;*/\r\n}\r\n\r\ndiv\r\n{&nbsp;//회전을&nbsp;시킨다.\r\n&nbsp;&nbsp;&nbsp;transform:&nbsp;skew(30deg,20deg);\r\n&nbsp;&nbsp;&nbsp;-ms-transform:&nbsp;skew(30deg,20deg);&nbsp;/*&nbsp;IE&nbsp;9&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;-webkit-transform:&nbsp;skew(30deg,20deg);&nbsp;/*&nbsp;Safari&nbsp;and&nbsp;Chrome&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;-o-transform:&nbsp;skew(30deg,20deg);&nbsp;/*&nbsp;Opera&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;-moz-transform:&nbsp;skew(30deg,20deg);&nbsp;/*&nbsp;Firefox&nbsp;*/\r\n}\r\n\r\ndiv\r\n{&nbsp;&nbsp;//transform:matrix(rotate,scale,traslate,skew);\r\n&nbsp;&nbsp;&nbsp;transform:matrix(0.866,0.5,-0.5,0.866,0,0);\r\n&nbsp;&nbsp;&nbsp;-ms-transform:matrix(0.866,0.5,-0.5,0.866,0,0);&nbsp;/*&nbsp;IE&nbsp;9&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;-moz-transform:matrix(0.866,0.5,-0.5,0.866,0,0);&nbsp;/*&nbsp;Firefox&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;-webkit-transform:matrix(0.866,0.5,-0.5,0.866,0,0);&nbsp;/*&nbsp;Safari&nbsp;and&nbsp;Chrome&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;-o-transform:matrix(0.866,0.5,-0.5,0.866,0,0);&nbsp;/*&nbsp;Opera&nbsp;*/\r\n}', '2012-12-08 15:20:57', '0000-00-00 00:00:00', ''),
(121, '3D Transform', 'Jquery', '', 'div\r\n{\r\ntransform:&nbsp;rotateX(120deg);\r\n-webkit-transform:&nbsp;rotateX(120deg);&nbsp;/*&nbsp;Safari&nbsp;and&nbsp;Chrome&nbsp;*/\r\n-moz-transform:&nbsp;rotateX(120deg);&nbsp;/*&nbsp;Firefox&nbsp;*/\r\n}\r\n\r\ndiv\r\n{\r\ntransform:&nbsp;rotateY(130deg);\r\n-webkit-transform:&nbsp;rotateY(130deg);&nbsp;/*&nbsp;Safari&nbsp;and&nbsp;Chrome&nbsp;*/\r\n-moz-transform:&nbsp;rotateY(130deg);&nbsp;/*&nbsp;Firefox&nbsp;*/\r\n}\r\n\r\ntranslate3d(x,y,z);\r\ntranslateX(x)\r\ntranslateY(y)\r\ntranslateZ(z)\r\nscale3d(x,y,z)\r\nscaleX(x)\r\nscaleY(y)\r\nscaleZ(z)\r\nrotate3d(x,y,z,angle)\r\nrotateX(angle)\r\nrotateY(angle)\r\nrotateZ(angle)\r\n', '2012-12-08 15:24:10', '0000-00-00 00:00:00', ''),
(122, 'Transitions', 'Jquery', '', '항상써줘야됨\r\ndiv:hover\r\n{\r\n    width:400px;\r\n}\r\n\r\ndiv\r\n{\r\ntransition: width 2s;\r\n-moz-transition: width 2s; /* Firefox 4 */\r\n-webkit-transition: width 2s; /* Safari and Chrome */\r\n-o-transition: width 2s; /* Opera */\r\n}\r\n가로를 2배로\r\n\r\ndiv //마우스를 올리면 회전하면서 2배로\r\n{\r\ntransition: width 2s, height 2s, transform 2s;\r\n-moz-transition: width 2s, height 2s, -moz-transform 2s;\r\n-webkit-transition: width 2s, height 2s, -webkit-transform 2s;\r\n-o-transition: width 2s, height 2s,-o-transform 2s;\r\n}\r\n\r\ndiv //2초뒤어 가로 커짐\r\n{\r\ntransition: width 1s linear 2s;\r\n/* Firefox 4 */\r\n-moz-transition:width 1s linear 2s;\r\n/* Safari and Chrome */\r\n-webkit-transition:width 1s linear 2s;\r\n/* Opera */\r\n-o-transition:width 1s linear 2s;\r\n}', '2012-12-08 15:31:42', '2012-12-08 15:33:13', ''),
(123, 'Animation', 'CSS3', '', '@keyframes을&nbsp;사용하여&nbsp;애니매이션&nbsp;효과를&nbsp;줌\r\n\r\ndiv\r\n{\r\nwidth:100px;\r\nheight:100px;\r\nbackground:red;\r\nanimation:myfirst&nbsp;5s;\r\n-moz-animation:myfirst&nbsp;5s;&nbsp;/*&nbsp;Firefox&nbsp;*/\r\n-webkit-animation:myfirst&nbsp;5s;&nbsp;/*&nbsp;Safari&nbsp;and&nbsp;Chrome&nbsp;*/\r\n-o-animation:myfirst&nbsp;5s;&nbsp;/*&nbsp;Opera&nbsp;*/\r\n}\r\n\r\n@keyframes&nbsp;myfirst\r\n{\r\nfrom&nbsp;{background:red;}\r\nto&nbsp;{background:yellow;}\r\n}\r\n\r\n@-moz-keyframes&nbsp;myfirst&nbsp;/*&nbsp;Firefox&nbsp;*/\r\n{\r\nfrom&nbsp;{background:red;}\r\nto&nbsp;{background:yellow;}\r\n}\r\n\r\n@-webkit-keyframes&nbsp;myfirst&nbsp;/*&nbsp;Safari&nbsp;and&nbsp;Chrome&nbsp;*/\r\n{\r\nfrom&nbsp;{background:red;}\r\nto&nbsp;{background:yellow;}\r\n}\r\n\r\n@-o-keyframes&nbsp;myfirst&nbsp;/*&nbsp;Opera&nbsp;*/\r\n{\r\nfrom&nbsp;{background:red;}\r\nto&nbsp;{background:yellow;}\r\n}', '2012-12-08 15:39:14', '0000-00-00 00:00:00', ''),
(124, 'Multiple Columns', 'CSS3', '', 'div&nbsp;//글들을&nbsp;3개로&nbsp;쪼갠다.\r\n{\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-moz-column-count:3;&nbsp;/*&nbsp;Firefox&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-webkit-column-count:3;&nbsp;/*&nbsp;Safari&nbsp;and&nbsp;Chrome&nbsp;*/\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;column-count:3;\r\n}\r\n\r\ndiv&nbsp;//문단&nbsp;사이를&nbsp;40px로\r\n{\r\n-moz-column-gap:40px;&nbsp;/*&nbsp;Firefox&nbsp;*/\r\n-webkit-column-gap:40px;&nbsp;/*&nbsp;Safari&nbsp;and&nbsp;Chrome&nbsp;*/\r\ncolumn-gap:40px;\r\n}\r\n\r\ndiv&nbsp;//문단&nbsp;규칙\r\n{\r\n-moz-column-rule:3px&nbsp;outset&nbsp;#ff00ff;&nbsp;/*&nbsp;Firefox&nbsp;*/\r\n-webkit-column-rule:3px&nbsp;outset&nbsp;#ff00ff;&nbsp;/*&nbsp;Safari&nbsp;and&nbsp;Chrome&nbsp;*/\r\ncolumn-rule:3px&nbsp;outset&nbsp;#ff00ff;\r\n}', '2012-12-08 15:41:37', '0000-00-00 00:00:00', ''),
(125, 'User Interface', 'CSS3', '', 'div\r\n{\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;resize&nbsp;:&nbsp;both;&nbsp;//리사이즈&nbsp;할&nbsp;수&nbsp;있게&nbsp;해줌\r\n}\r\n', '2012-12-08 16:00:32', '0000-00-00 00:00:00', ''),
(126, 'OSMU', '영어', '', 'One&nbsp;Source&nbsp;Multi&nbsp;Use.', '2012-12-08 16:38:42', '0000-00-00 00:00:00', ''),
(127, '반응형 웹', '여러가지', '', 'Css&nbsp;파일을&nbsp;적게&nbsp;사용&nbsp;할&nbsp;수록&nbsp;HTTP요청이&nbsp;줄어&nbsp;들아&nbsp;로딩이&nbsp;빠름\r\n\r\n이미지를&nbsp;적게사용&nbsp;할&nbsp;수록&nbsp;로딩이&nbsp;적음\r\n\r\nJs&nbsp;파일을&nbsp;병합하여&nbsp;성능개선\r\n\r\n추천하는&nbsp;js삽입&nbsp;위치\r\nBody영역에&nbsp;삽입하면&nbsp;모두&nbsp;화면에&nbsp;출력&nbsp;된후&nbsp;해석\r\n\r\n뷰&nbsp;포트&nbsp;설정\r\n&lt;meta&nbsp;name=&quot;viewport&quot;&nbsp;content=&quot;width=device-width,&nbsp;initial-scale=1,minimum-scale=1,&nbsp;maximum-scale=1,user-scalable=no&quot;&nbsp;/&gt;\r\n', '2012-12-08 16:52:23', '0000-00-00 00:00:00', ''),
(128, 'html5 semantics', 'HTML5', '', 'Header&nbsp;사이트&nbsp;제목&nbsp;또는&nbsp;분문&nbsp;헤더\r\nFooter&nbsp;사이트&nbsp;풋터&nbsp;또는&nbsp;본문&nbsp;풋터\r\nSection&nbsp;하나의&nbsp;주제로&nbsp;구성된&nbsp;콘텐츠&nbsp;또는&nbsp;애플리케이션&nbsp;블럭\r\nArticle&nbsp;본문&nbsp;콘텐츠로서&nbsp;주변과&nbsp;분리해도&nbsp;하나의&nbsp;완전한&nbsp;콘텐츠다&nbsp;되는&nbsp;영역\r\nNav&nbsp;애플리케이션&nbsp;조작을&nbsp;위한&nbsp;버튼&nbsp;그룹\r\nMenu&nbsp;애플리케이션&nbsp;조작을&nbsp;위한&nbsp;버튼&nbsp;그룹\r\nAside&nbsp;주요한&nbsp;내용이&nbsp;아닌&nbsp;부가적인&nbsp;콘텐츠', '2012-12-08 17:04:08', '0000-00-00 00:00:00', '');

-- --------------------------------------------------------

--
-- 테이블 구조 `member`
--

CREATE TABLE IF NOT EXISTS `member` (
  `no` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(100) NOT NULL,
  `pwd` varchar(100) NOT NULL,
  `lv` varchar(10) NOT NULL,
  PRIMARY KEY (`no`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

--
-- 테이블의 덤프 데이터 `member`
--

INSERT INTO `member` (`no`, `email`, `pwd`, `lv`) VALUES
(1, 'koreaskills', '*6F664610796D314D141A1E825CE5630DB8DCCFC2', '10');

-- --------------------------------------------------------

--
-- 테이블 구조 `menu`
--

CREATE TABLE IF NOT EXISTS `menu` (
  `no` int(11) NOT NULL AUTO_INCREMENT,
  `main_id` varchar(20) NOT NULL,
  `sub_id` varchar(20) NOT NULL,
  `type` varchar(20) NOT NULL,
  `title` varchar(20) NOT NULL,
  `od` varchar(2) NOT NULL,
  `hd` varchar(2) NOT NULL,
  PRIMARY KEY (`no`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=44 ;

--
-- 테이블의 덤프 데이터 `menu`
--

INSERT INTO `menu` (`no`, `main_id`, `sub_id`, `type`, `title`, `od`, `hd`) VALUES
(11, 'JQUERY', '', 'main', 'JQUERY', '', '1'),
(12, 'JQUERY', 'Jquery', 'board', 'Jquery', '', ''),
(13, 'JQUERY', 'Jquery UI', 'board', 'Jquery UI', '', ''),
(14, 'JQUERY', 'Jquery Mobile', 'board', 'Jquery Mobile', '', ''),
(15, 'HTML &amp; CSS', '', 'main', 'HTML &amp; CSS', '', '1'),
(16, 'HTML &amp; CSS', 'HTML5', 'board', 'HTML5', '', ''),
(17, 'HTML &amp; CSS', 'CSS3', 'board', 'CSS3', '', ''),
(18, 'login', '', 'main', '로그인', '', ''),
(19, 'login', 'login', 'login', '로그인', '', ''),
(20, 'login', 'logout', 'logout', '로그아웃', '', ''),
(21, 'board', '', 'main', '콘텐츠 관리', '', ''),
(22, 'board', 'write', 'write', '글쓰기', '', ''),
(23, 'board', 'modify', 'modify', '수정', '', ''),
(24, 'board', 'delete', 'delete', '삭제', '', ''),
(25, 'admin', '', 'main', '관리자페이지', '', ''),
(26, 'admin', 'cateadmin', 'cateadmin', '카테고리관리', '', ''),
(31, 'other', '', 'main', '기타', '', '1'),
(32, 'other', 'other', 'board', '여러가지', '', ''),
(33, 'other', 'eng', 'board', '영어', '', ''),
(42, 'search', '', 'main', '검색', '', ''),
(43, 'search', 'search', 'search', '검색', '', '');
